package brazoroboticoconarduino;

/**
 *
 * @author Orlando Mozqueda
 */
import com.panamahitek.ArduinoException;
import com.panamahitek.PanamaHitek_Arduino;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import jssc.SerialPortEvent;
import jssc.SerialPortEventListener;
import jssc.SerialPortException;

public class InterfazBrazoRobotico extends javax.swing.JFrame {

    /**
     * Creates new form Ventanaç
     */
    String puerta = "COM9";

    public InterfazBrazoRobotico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private PanamaHitek_Arduino ino = new PanamaHitek_Arduino();
    private SerialPortEventListener listener = new SerialPortEventListener() {
        @Override
        public void serialEvent(SerialPortEvent spe) {
            try {
                if (ino.isMessageAvailable()) {
                    //temp.setText(ino.printMessage()+"º C");

                }
            } catch (SerialPortException | ArduinoException ex) {
                Logger.getLogger(InterfazBrazoRobotico.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    };

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Izquierda = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        puerto = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        comunicacion = new javax.swing.JButton();
        com = new javax.swing.JLabel();
        Derecha = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Detener = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        abajo = new javax.swing.JButton();
        arriba = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        AbajoMuneca = new javax.swing.JButton();
        ArribaMuneca = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Recoger = new javax.swing.JButton();
        Depositar = new javax.swing.JButton();
        Det = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Izquierda.setText("Izquierda");
        Izquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzquierdaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Comunicacion con Arduino");

        puerto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9", "COM18" }));

        jLabel5.setText("Puerto:");

        comunicacion.setText("Comunicar");
        comunicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comunicacionActionPerformed(evt);
            }
        });

        com.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        com.setForeground(new java.awt.Color(255, 0, 0));
        com.setText("Desconectado");

        Derecha.setText("Derecha");
        Derecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DerechaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Girar brazo");

        Detener.setText("Detener");
        Detener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetenerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Movimiento del hombro");

        abajo.setText("Abajo");
        abajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abajoActionPerformed(evt);
            }
        });

        arriba.setText("Arriba");
        arriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arribaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Movimiento de la muñeca");

        AbajoMuneca.setText("Abajo");
        AbajoMuneca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbajoMunecaActionPerformed(evt);
            }
        });

        ArribaMuneca.setText("Arriba");
        ArribaMuneca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArribaMunecaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Movimiento de la mano");

        jButton1.setText("Agarrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Soltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Automatizado brazo robotico");

        Recoger.setText("Recoger");
        Recoger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecogerActionPerformed(evt);
            }
        });

        Depositar.setText("Depositar");
        Depositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositarActionPerformed(evt);
            }
        });

        Det.setText("Detener");
        Det.setEnabled(false);
        Det.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Recoger)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Depositar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Det))
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AbajoMuneca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ArribaMuneca))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(abajo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arriba))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comunicacion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(com))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Izquierda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Derecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Detener)))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(comunicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(com)
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Derecha)
                        .addComponent(Detener))
                    .addComponent(Izquierda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abajo)
                    .addComponent(arriba))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AbajoMuneca)
                    .addComponent(ArribaMuneca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Recoger)
                    .addComponent(Depositar)
                    .addComponent(Det))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzquierdaActionPerformed
        //Cambiamos el color del boton
        Derecha.setBackground(java.awt.Color.WHITE);
        //Cambiamos el color del boton
        Izquierda.setBackground(java.awt.Color.GREEN);
        //Cambiamos el color del boton
        Detener.setBackground(java.awt.Color.WHITE);
        try {
            //Aqui se envia por el serial lo que va recibir el arduino
            ino.sendData("2");
        } catch (ArduinoException | SerialPortException ex) {
            Logger.getLogger(InterfazBrazoRobotico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IzquierdaActionPerformed

    private void comunicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comunicacionActionPerformed
        //En estas decisiones se va traer el valor del puerto que fue seleccionado      
        if (puerto.getSelectedItem() == "COM1") {
            puerta = "COM1";
        }
        if (puerto.getSelectedItem() == "COM2") {
            puerta = "COM2";
        }
        if (puerto.getSelectedItem() == "COM3") {
            puerta = "COM3";
        }
        if (puerto.getSelectedItem() == "COM4") {
            puerta = "COM4";
        }
        if (puerto.getSelectedItem() == "COM5") {
            puerta = "COM5";
        }
        if (puerto.getSelectedItem() == "COM6") {
            puerta = "COM6";
        }
        if (puerto.getSelectedItem() == "COM7") {
            puerta = "COM7";
        }
        if (puerto.getSelectedItem() == "COM8") {
            puerta = "COM8";
        }
        if (puerto.getSelectedItem() == "COM9") {
            puerta = "COM9";
        }
        if (puerto.getSelectedItem() == "COM18") {
            puerta = "COM18";
        }
        try {
            //Aqui se hace la conexion hacia el arduino
            //Seleccionamos el puerto
            //La velocidad de comunicacion del serial
            //El metodo utilizado para hacer los envios y tambien recibirlos
            ino.arduinoRXTX(puerta, 9600, listener);
            com.setText("Conectado");
            com.setForeground(new java.awt.Color(0, 204, 0));
        } catch (ArduinoException ex) {
            Logger.getLogger(InterfazBrazoRobotico.class.getName()).log(Level.SEVERE, null, ex);
            com.setText("Desconectado");
            com.setForeground(new java.awt.Color(255, 0, 0));
        }
    }//GEN-LAST:event_comunicacionActionPerformed

    private void DerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DerechaActionPerformed
        //Cambiamos el color del boton
        Derecha.setBackground(java.awt.Color.GREEN);
        //Cambiamos el color del boton
        Izquierda.setBackground(java.awt.Color.WHITE);
        //Cambiamos el color del boton
        Detener.setBackground(java.awt.Color.WHITE);
        try {
            //Aqui se envia por el serial lo que va recibir el arduino
            ino.sendData("1");
        } catch (ArduinoException | SerialPortException ex) {
            Logger.getLogger(InterfazBrazoRobotico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DerechaActionPerformed

    private void DetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetenerActionPerformed
        Derecha.setBackground(java.awt.Color.WHITE);
        Izquierda.setBackground(java.awt.Color.WHITE);
        Detener.setBackground(java.awt.Color.RED);
        try {
            //Aqui se envia por el serial lo que va recibir el arduino
            ino.sendData("3");
        } catch (ArduinoException | SerialPortException ex) {
            Logger.getLogger(InterfazBrazoRobotico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DetenerActionPerformed

    private void abajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abajoActionPerformed
        //Cambiamos el color del boton
        abajo.setBackground(java.awt.Color.GREEN);
        //Cambiamos el color del boton
        arriba.setBackground(java.awt.Color.WHITE);
        try {
            //Aqui se envia por el serial lo que va recibir el arduino
            ino.sendData("4");
        } catch (ArduinoException | SerialPortException ex) {
            Logger.getLogger(InterfazBrazoRobotico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_abajoActionPerformed

    private void arribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arribaActionPerformed
        //Cambiamos el color del boton
        abajo.setBackground(java.awt.Color.WHITE);
        //Cambiamos el color del boton
        arriba.setBackground(java.awt.Color.GREEN);
        try {
            //Aqui se envia por el serial lo que va recibir el arduino
            ino.sendData("5");
        } catch (ArduinoException | SerialPortException ex) {
            Logger.getLogger(InterfazBrazoRobotico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_arribaActionPerformed

    private void AbajoMunecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbajoMunecaActionPerformed
        //Cambiamos el color del boton        
        AbajoMuneca.setBackground(java.awt.Color.GREEN);
        //Cambiamos el color del boton
        ArribaMuneca.setBackground(java.awt.Color.WHITE);
        try {
            //Aqui se envia por el serial lo que va recibir el arduino
            ino.sendData("6");
        } catch (ArduinoException | SerialPortException ex) {
            Logger.getLogger(InterfazBrazoRobotico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AbajoMunecaActionPerformed

    private void ArribaMunecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArribaMunecaActionPerformed
        //Cambiamos el color del boton
        AbajoMuneca.setBackground(java.awt.Color.WHITE);
        //Cambiamos el color del boton
        ArribaMuneca.setBackground(java.awt.Color.GREEN);
        try {
            //Aqui se envia por el serial lo que va recibir el arduino
            ino.sendData("7");
        } catch (ArduinoException | SerialPortException ex) {
            Logger.getLogger(InterfazBrazoRobotico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ArribaMunecaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Cambiamos el color del boton
        jButton1.setBackground(java.awt.Color.GREEN);
        //Cambiamos el color del boton
        jButton2.setBackground(java.awt.Color.WHITE);
        try {
            //Aqui se envia por el serial lo que va recibir el arduino
            ino.sendData("8");
        } catch (ArduinoException | SerialPortException ex) {
            Logger.getLogger(InterfazBrazoRobotico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       //Cambiamos el color del boton
        jButton2.setBackground(java.awt.Color.GREEN);
        //Cambiamos el color del boton
       jButton1.setBackground(java.awt.Color.WHITE);
        try {
            //Aqui se envia por el serial lo que va recibir el arduino
            ino.sendData("9");
        } catch (ArduinoException | SerialPortException ex) {
            Logger.getLogger(InterfazBrazoRobotico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void RecogerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecogerActionPerformed
        //Cambiamos el color del boton
        Recoger.setBackground(java.awt.Color.GREEN);
        //Cambiamos el color del boton
        Depositar.setBackground(java.awt.Color.WHITE);
        //Cambiamos el color del boton
        Det.setBackground(java.awt.Color.WHITE);
        try {
            //Aqui se envia por el serial lo que va recibir el arduino
            ino.sendData("0");
        } catch (ArduinoException | SerialPortException ex) {
            Logger.getLogger(InterfazBrazoRobotico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RecogerActionPerformed

    private void DepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositarActionPerformed
        //Cambiamos el color del boton
        Recoger.setBackground(java.awt.Color.WHITE);
        //Cambiamos el color del boton
        Depositar.setBackground(java.awt.Color.GREEN);
        //Cambiamos el color del boton
        Det.setBackground(java.awt.Color.WHITE);
        try {
            //Aqui se envia por el serial lo que va recibir el arduino
            ino.sendData("A");
        } catch (ArduinoException | SerialPortException ex) {
            Logger.getLogger(InterfazBrazoRobotico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DepositarActionPerformed

    private void DetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetActionPerformed
        //Cambiamos el color del boton
        Recoger.setBackground(java.awt.Color.WHITE);
        //Cambiamos el color del boton
        Depositar.setBackground(java.awt.Color.WHITE);
        //Cambiamos el color del boton
        Det.setBackground(java.awt.Color.RED);
        try {
            //Aqui se envia por el serial lo que va recibir el arduino
            ino.sendData("B");
        } catch (ArduinoException | SerialPortException ex) {
            Logger.getLogger(InterfazBrazoRobotico.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_DetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazBrazoRobotico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazBrazoRobotico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazBrazoRobotico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazBrazoRobotico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazBrazoRobotico().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbajoMuneca;
    private javax.swing.JButton ArribaMuneca;
    private javax.swing.JButton Depositar;
    private javax.swing.JButton Derecha;
    private javax.swing.JButton Det;
    private javax.swing.JButton Detener;
    private javax.swing.JButton Izquierda;
    private javax.swing.JButton Recoger;
    private javax.swing.JButton abajo;
    private javax.swing.JButton arriba;
    private javax.swing.JLabel com;
    private javax.swing.JButton comunicacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> puerto;
    // End of variables declaration//GEN-END:variables
}
